# Generated by Django 4.1.4 on 2023-03-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='description',
            new_name='title',
        ),
    ]
