# Generated by Django 4.1.4 on 2023-03-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0005_alter_firewallrule_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ANY', 'ANY')], default='TCP', max_length=10),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='type',
            field=models.CharField(choices=[('CUSTOM TCP', 'CUSTOM TCP'), ('CUSTOM UDP', 'CUSTOM UDP'), ('CUSTOM ICMP', 'CUSTOM ICMP'), ('ALL TCP', 'ALL TCP'), ('ALL UDP', 'ALL UDP'), ('ALL ICMP', 'ALL ICMP'), ('ALL TRAFFIC', 'ALL TRAFFIC'), ('SSH 22', 'SSH 22'), ('TELNET 23', 'TELNET 23'), ('SMTP 25', 'SMTP 25'), ('NAMESERVER 42', 'NAMESERVER 42'), ('DNS UDP 53', 'DNS UDP 53'), ('DNS TCP 53', 'DNS TCP 53'), ('HTTP 80', 'HTTP 80'), ('POP3 110', 'POP3 110'), ('IMAP 143', 'IMAP 143'), ('LDAP 389', 'LDAP 389'), ('HTTPS 443', 'HTTPS 443'), ('SMB 445', 'SMB 445'), ('SMTPS 465', 'SMTPS 465'), ('IMAPS 993', 'IMAPS 993'), ('POP3S 995', 'POP3S 995'), ('NFS 2049', 'NFS 2049')], default='CUSTOM TCP', max_length=50),
        ),
    ]
