# Generated by Django 4.1.4 on 2023-03-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0006_alter_firewallrule_protocol_alter_firewallrule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], default='TCP', max_length=10),
        ),
    ]
