# Generated by Django 4.1.4 on 2023-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0010_alter_firewallrule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='rule_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='firewallrule',
            unique_together={('rule_id', 'traffic_direction', 'ip_family')},
        ),
    ]
