# Generated by Django 4.1.4 on 2023-04-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0012_rename_id_firewallrule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
