# Generated by Django 4.1.4 on 2023-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0015_alter_firewallrule_traffic_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='traffic_direction',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Inbound', max_length=30),
        ),
    ]
