# Generated by Django 4.1.4 on 2023-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0008_alter_firewallrule_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
