# Generated by Django 4.1.4 on 2023-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0013_alter_firewallrule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='destination_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='source_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
